# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

services:
  minio:
    build:
      context: minio
    container_name: docker-minio_${PROJECT_NAME}
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio-net
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpsw
    volumes:
      - ${MINIO_DATA_VOLUME}:/mnt/data
  minio-mc:
    build:
      context: minio-mc
    container_name: docker-minio-mc_${PROJECT_NAME}
    restart: always
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge
